# Generated by Django 4.0.5 on 2022-07-27 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_email', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
