# Generated by Django 4.0.5 on 2022-07-27 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(max_length=20)),
                ('locality', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=70)),
                ('address', models.TextField(max_length=300)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=70)),
                ('profile_image', models.FileField(blank=True, upload_to='user_profile_image')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfileModel',
        ),
    ]
