# Generated by Django 4.0.6 on 2022-08-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_cart_product_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='user_profile_image'),
        ),
    ]
